### ISSUE TITLE
How to get ground_truth

### ISSUE THREAD

**Issue by othmanalsawaf** [Novartis/granulator#1]
Dear granulator_team,

Thank you for providing this fantastic tool.
In the tutorial, you suggest using a ground_truth file to benchmark the various deconvolution methods. How should this "ground_truth" be retrieved in practise, e.g. what kind of data would constitute the ground truth if I have a bulk expression dataset from a solid tumor?

Thanks ever so much.

Best wishes
Othman

**Comment by xanibas** [comment]
please refer to granulator version that is installed Bioconductor [here](https://github.com/xanibas/granulator), including an updated [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html). This package is legacy code.
