### ISSUE TITLE
Error running some methods when deconvolution

### ISSUE THREAD

**Issue by moutazhelal** [Novartis/granulator#2]
Dear Authors ,

Thank you for reading my message.

I was trying to run deconvolution on my Bulk RNA seq data with multiple samples and I found your to be convenient as I had problems deciding on which method to use. I have my sample matrix as normalized TPMs and I obtained gene signatures of cell types from "celldex" and transformed the provide log counts (normalized as TPM) using :
`TPMs_count  = exp(log_counts)`
and I ran this  
`> decon_rls <- deconvolute(m = TomEMD_dec, sigMatrix = cell_types_means_m, "rls", use_cores= 1)`
and obtained this error only running  rls 
> Running deconvolution method "rls" on signature matrix "sig1"
> Error in rlm.default(df$x, as.vector(z), maxit = 1000, psi = psi.huber) : 
>   'x' is singular: singular fits are not implemented in 'rlm'

and this error when running dtangle
`
`> decon_dtangle <- deconvolute(m = TomEMD_dec, sigMatrix = cell_types_means_m, "dtangle", use_cores= 1)

> Running deconvolution method "dtangle" on signature matrix "sig1"
> Warning message:
> In max(rowSums(x), na.rm = TRUE) :
>   no non-missing arguments to max; returning -Inf

and when running `svr` it run nonstop without finishing 

other methods like `'ols','nnls','qprog'` run without any problem

Could you help me ?

Thanks,
Best

**Comment by xanibas** [comment]
please refer to granulator version that is installed Bioconductor [here](https://github.com/xanibas/granulator), including an updated [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html). This package is legacy code.
