### ISSUE TITLE
Error in order(colnames(x)) : argument 1 is not a vector

### ISSUE THREAD

**Issue by nbutyrate** [Novartis/granulator#3]
HI I am doing the following.

decon <- deconvolute(m = tata, sigMatrix = sigList)

and getting following erroe

Error in order(colnames(x)) : argument 1 is not a vector

and my data is 

str(tata)
 int [1:55365, 1:60] 0 0 212 16 35 807 12 0 447 1 ...
 - attr(*, "dimnames")=List of 2
  ..$ : chr [1:55365] "0610005C13Rik" "0610006L08Rik" "0610009B22Rik" "0610009E02Rik" ...
  ..$ : chr [1:60] "GC.SL.625_1" "GC.SL.625_2" "GC.SL.625_3" "GC.SL.625_4" ...

**Comment by xanibas** [comment]
please refer to granulator version that is installed Bioconductor [here](https://github.com/xanibas/granulator), including an updated [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html). This package is legacy code.
