### ISSUE TITLE
How to interpret correlation heatmap and choose the right reference matrix and algorithm

### ISSUE THREAD

**Issue by Pamelanmrc** [Novartis/granulator#4]

**Comment by Pamelanmrc** [comment]
Hi,
Thank you for writing this piece of software. It is extremely useful. I would like to know how to interpret the correlation of all methods without the ground truth. How does one pick the algorithm and matrix to decide which matrix and algorithm to select for your dataset. Also what's the y axis for the heatmap in the correlation heatmap?

**Comment by xanibas** [comment]
Hi, please refer to granulator version that is installed by Bioconductor [here](https://github.com/xanibas/granulator), including an updated [vignette](https://www.bioconductor.org/packages/release/bioc/vignettes/granulator/inst/doc/granulator.html). This package is legacy code. If you have still questions, post them in the respective [issue](https://github.com/xanibas/granulator/issues) section.
